main: fr.will33.neisisminage.NeisisMinagePlugin
name: NeisisMinagePlugin
version: ${project.version}
author: William AVENTIN
website: https://www.elesia.org
commands:
  xpmine:
  pointsmine:
  minepointsadd:
  minepoints:
  minepointsreset:
  minepointstake:
  minexp:
  minexpreset:
  minexpadd:
  minexpremove:
  mineshop:
  minageshopcreate: